### ISSUE TITLE
Request for GUI Source Code

### ISSUE THREAD

**Issue by NewmanNya** [parhambt/MRI-brain-tumor-detection#3]
Dear Sir,
I hope this message finds you well. I am an enthusiastic user of your project and greatly appreciate the effort you've put into making it open source.

I have been exploring the project thoroughly and find it to be a valuable tool for my class work. However, I noticed that the GUI source code is not available in the repository. As someone interested in understanding the inner workings of the GUI and potentially contributing to its improvement, I was wondering if you could kindly provide the source code for the GUI.

Having access to the GUI source code would not only help me in enhancing my understanding of the project but also enable me to contribute more effectively by submitting relevant bug reports or proposing new features.

I understand that maintaining an open-source project requires a significant amount of time and effort, and I truly appreciate the work you've already done. Your consideration of this request would mean a lot to the community of users who, like me, are eager to delve deeper into the project.

Thank you for your time and for creating such a valuable resource for the community. I look forward to your response.

Best regards

**Comment by parhambt** [comment]
Hello
I am very happy that this project is useful for you
The source code of the graphic application is in the backend interface AI directory in repo check it out  .
I hope it was useful

**Comment by NewmanNya** [comment]
I haven't use https://git-lfs.com/ before. I will try to learn how to use it.  Best wishes for u.  Your code is very very very very very very usefully for me~
